//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowsFormsApp1.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Ảnh_chụp_màn_hình_2024_11_20_222924 {
            get {
                object obj = ResourceManager.GetObject("Ảnh chụp màn hình 2024-11-20 222924", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Ảnh_chụp_màn_hình_2024_11_20_223820 {
            get {
                object obj = ResourceManager.GetObject("Ảnh chụp màn hình 2024-11-20 223820", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Ảnh_chụp_màn_hình_2024_11_20_224224 {
            get {
                object obj = ResourceManager.GetObject("Ảnh chụp màn hình 2024-11-20 224224", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Ảnh_chụp_màn_hình_2024_11_20_224302 {
            get {
                object obj = ResourceManager.GetObject("Ảnh chụp màn hình 2024-11-20 224302", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Ảnh_chụp_màn_hình_2024_11_20_224351 {
            get {
                object obj = ResourceManager.GetObject("Ảnh chụp màn hình 2024-11-20 224351", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Ảnh_chụp_màn_hình_2024_11_20_224439 {
            get {
                object obj = ResourceManager.GetObject("Ảnh chụp màn hình 2024-11-20 224439", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Ảnh_chụp_màn_hình_2024_11_20_224724 {
            get {
                object obj = ResourceManager.GetObject("Ảnh chụp màn hình 2024-11-20 224724", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Ảnh_chụp_màn_hình_2024_11_20_230107 {
            get {
                object obj = ResourceManager.GetObject("Ảnh chụp màn hình 2024-11-20 230107", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Ảnh_chụp_màn_hình_2024_11_20_230132 {
            get {
                object obj = ResourceManager.GetObject("Ảnh chụp màn hình 2024-11-20 230132", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Ảnh_chụp_màn_hình_2024_11_21_131853 {
            get {
                object obj = ResourceManager.GetObject("Ảnh chụp màn hình 2024-11-21 131853", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Ảnh_chụp_màn_hình_2024_11_21_132023 {
            get {
                object obj = ResourceManager.GetObject("Ảnh chụp màn hình 2024-11-21 132023", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Ảnh_chụp_màn_hình_2024_11_21_132126 {
            get {
                object obj = ResourceManager.GetObject("Ảnh chụp màn hình 2024-11-21 132126", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Ảnh_chụp_màn_hình_2024_11_21_132336 {
            get {
                object obj = ResourceManager.GetObject("Ảnh chụp màn hình 2024-11-21 132336", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Ảnh_chụp_màn_hình_2024_11_21_171021 {
            get {
                object obj = ResourceManager.GetObject("Ảnh chụp màn hình 2024-11-21 171021", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Ảnh_chụp_màn_hình_2024_11_21_171302 {
            get {
                object obj = ResourceManager.GetObject("Ảnh chụp màn hình 2024-11-21 171302", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Ảnh_chụp_màn_hình_2024_11_21_171633 {
            get {
                object obj = ResourceManager.GetObject("Ảnh chụp màn hình 2024-11-21 171633", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Ảnh_chụp_màn_hình_2024_11_21_173044 {
            get {
                object obj = ResourceManager.GetObject("Ảnh chụp màn hình 2024-11-21 173044", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Ảnh_chụp_màn_hình_2024_11_21_173346 {
            get {
                object obj = ResourceManager.GetObject("Ảnh chụp màn hình 2024-11-21 173346", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Ảnh_chụp_màn_hình_2024_11_23_153454 {
            get {
                object obj = ResourceManager.GetObject("Ảnh chụp màn hình 2024-11-23 153454", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Ảnh_chụp_màn_hình_2024_11_23_153707 {
            get {
                object obj = ResourceManager.GetObject("Ảnh chụp màn hình 2024-11-23 153707", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Ảnh_chụp_màn_hình_2024_11_23_153754 {
            get {
                object obj = ResourceManager.GetObject("Ảnh chụp màn hình 2024-11-23 153754", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Ảnh_chụp_màn_hình_2024_11_23_153838 {
            get {
                object obj = ResourceManager.GetObject("Ảnh chụp màn hình 2024-11-23 153838", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Ảnh_chụp_màn_hình_2024_11_23_153942 {
            get {
                object obj = ResourceManager.GetObject("Ảnh chụp màn hình 2024-11-23 153942", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pngtree_add_icon_isolated_on_abstract_background_png_image_1742619 {
            get {
                object obj = ResourceManager.GetObject("pngtree-add-icon-isolated-on-abstract-background-png-image_1742619", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
